name: org-to-smos
version: '0.0.0.0'
category: Tool
author: Kieran Trezona-le Comte & Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos

default-extensions:
- NoImplicitPrelude

dependencies:
- parsec
- base >=4.9 && <=5
- bytestring
- smos
- smos-data
- text
- optparse-applicative
- path
- path-io
- hspec

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Smos.OrgToSmos

executables:
  org-to-smos:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - org-to-smos
    default-extensions:
    - ImplicitPrelude

tests:
  org-to-smos-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hspec
    - smos
    - smos-data
    - smos-data-gen
    - org-to-smos
