name:                smos-convert
version:             0.1.0.0
github:              https://github.com/NorfairKing/smos
license:             AllRightsReserved
author:              Nick Van den Broeck
maintainer:          syd.kerckhove@gmail.com
copyright:           2018 Nick Van den Broeck

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/NorfairKing/smos>

dependencies:
- base >=4.7 && <5
- brick >=0.28 && <0.29
- bytestring >=0.10 && <0.11
- containers >=0.5 && <0.6
- cursor >=0.0 && <0.1
- fuzzy-time >=0.0 && <0.1
- megaparsec >=5.3 && <5.4
- microlens >=0.4 && <0.5
- mtl >=2.2 && <2.3
- optparse-applicative >=0.13 && <0.14
- path >=0.5 && <0.6
- path-io >=1.2 && <1.3
- process >=1.4 && <1.5
- safe >=0.3 && <0.4
- smos-data >=0.0 && <0.1
- text >=1.2 && <1.3
- time >=1.6 && <1.7
- unordered-containers >=0.2 && <0.3
- validity >=0.4 && <0.5
- validity-containers >=0.2 && <0.3
- validity-text >=0.2 && <0.3
- validity-time >=0.1 && <0.2
- validity-unordered-containers >=0.1 && <0.2
- vty >=5.18 && <5.19
- yaml >=0.8 && <0.9
- orgmode-parse >=0.2 && <0.3
- attoparsec >=0.13 && <0.14
- hashable >=1.2 && <1.3
- hspec >=2.4 && <2.5
- genvalidity-hspec >=0.5 && <0.6
- genvalidity-time >=0.1 && <0.2
- QuickCheck >=2.9 && <2.10
- thyme >=0.3 && <0.4
- genvalidity-text >=0.4 && <0.5

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Smos.Convert
  - Smos.Convert.Document
  - Smos.Convert.EntryTree
  - Smos.Convert.OptParse
  - Smos.Convert.SmosFile
  - Smos.Convert.Logbook
  - Smos.Convert.Time

executables:
  smos-convert:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smos-convert

tests:
  smos-convert-test:
    main:                Spec.hs
    source-dirs:         test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smos-convert
